### ISSUE TITLE
How to generate text without giving prefix ?

### ISSUE THREAD

**Issue by Atharva-Phatak** [yxuansu/SimCTG#3]
Let's say I want to generate text but without passing any prefix ?

How can I generate outputs without providing the prefix using the current code. 
Please let me know.

**Comment by yxuansu** [comment]
> 

Hi,

Thanks for your interest in our work! 

Our code currently does not support unconditional generation (i.e. generation without any prefix). In order to do that, you can re-train a SimCTG model with training sequences starting with the same sos token. Then, you could use techniques like diverse contrastive search (mentioned in appendix G of the paper) to generate some unconditional results. The implementation of diverse contrastive search can be found here (https://github.com/yxuansu/SimCTG/tree/main/document_generation#42-diverse-contrastive-search).

Please let me know if you have any further questions :-)
